name: buildjet

on: [push, pull_request]

permissions: {}

jobs:
  buildjet:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test buildjet provider on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./
        with:
          workspaces: tests
          cache-provider: buildjet

      - run: |
          cargo check
          cargo test
          cargo build --release
        working-directory: tests
