name: coverage

on: [push, pull_request]

permissions: {}

jobs:
  coverage:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo-llvm-cov` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - run: rustup toolchain install stable --profile minimal --component llvm-tools-preview --no-self-update

      - uses: taiki-e/install-action@3575e532701a5fc614b0c842e4119af4cc5fd16d # v2.62.60
        with:
          tool: cargo-llvm-cov

      - uses: ./
        with:
          workspaces: tests

      - run: cargo llvm-cov --all-features --workspace
        working-directory: tests
