name: coverage

on: [push, pull_request]

permissions: {}

jobs:
  coverage:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo-llvm-cov` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - run: rustup toolchain install stable --profile minimal --component llvm-tools-preview --no-self-update

      - uses: taiki-e/install-action@b9c5db3aef04caffaf95a1d03931de10fb2a140f # v2.65.1
        with:
          tool: cargo-llvm-cov

      - uses: ./
        with:
          workspaces: tests

      - run: cargo llvm-cov --all-features --workspace
        working-directory: tests
