name: git-registry

on: [push, pull_request]

permissions: {}

jobs:
  git-registry:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test cargo "git" registry on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./
        with:
          workspaces: tests

      - run: |
          cargo check
          cargo test
        working-directory: tests
