name: install

on: [push, pull_request]

permissions: {}

jobs:
  install:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo install` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./

      - run: cargo install cargo-deny --locked
