name: multi-job-cache

on: [push, pull_request]

permissions: {}

jobs:
  multi-job-cache-1:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test multi-job cache (1) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: install rust toolchain
        run: rustup toolchain install stable --profile minimal --target wasm32-unknown-unknown --no-self-update

      - name: cache
        uses: ./
        with:
          workspaces: |
            tests
          add-job-id-key: "false"
          add-rust-environment-hash-key: "false"

      - name: cargo check (tests)
        working-directory: tests
        run: cargo check

  multi-job-cache-2:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test multi-job cache (2) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: install rust toolchain
        run: rustup toolchain install stable --profile minimal --target wasm32-unknown-unknown --no-self-update

      - name: cache
        uses: ./
        with:
          workspaces: |
            tests/wasm-workspace
          add-job-id-key: "false"
          add-rust-environment-hash-key: "false"

      - name: cargo check (tests/wasm-workspace)
        working-directory: tests/wasm-workspace
        run: cargo check
