name: nix

on: [push, pull_request]

permissions: {}

jobs:
  nix:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Test Nix on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@7e5978947b7efba56e96c43fd785691980aca924 # v31.8.4

      - uses: ./
        with:
          workspaces: tests
          cmd-format: nix develop tests -c {0}

      - run: |
          nix develop -c cargo check --color always
          nix develop -c cargo test --color always
        working-directory: tests
