name: nix

on: [push, pull_request]

permissions: {}

jobs:
  nix:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Test Nix on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0

      - uses: ./
        with:
          workspaces: tests
          cmd-format: nix develop ./tests -c {0}

      - run: |
          nix develop -c cargo check
          nix develop -c cargo test
        working-directory: tests
